//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CMS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CMSEntities object using the connection string found in the 'CMSEntities' section of the application configuration file.
        /// </summary>
        public CMSEntities() : base("name=CMSEntities", "CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CMSEntities object.
        /// </summary>
        public CMSEntities(string connectionString) : base(connectionString, "CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CMSEntities object.
        /// </summary>
        public CMSEntities(EntityConnection connection) : base(connection, "CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Admission_Table> Admission_Table
        {
            get
            {
                if ((_Admission_Table == null))
                {
                    _Admission_Table = base.CreateObjectSet<Admission_Table>("Admission_Table");
                }
                return _Admission_Table;
            }
        }
        private ObjectSet<Admission_Table> _Admission_Table;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CMS_Table> CMS_Table
        {
            get
            {
                if ((_CMS_Table == null))
                {
                    _CMS_Table = base.CreateObjectSet<CMS_Table>("CMS_Table");
                }
                return _CMS_Table;
            }
        }
        private ObjectSet<CMS_Table> _CMS_Table;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<History> Histories
        {
            get
            {
                if ((_Histories == null))
                {
                    _Histories = base.CreateObjectSet<History>("Histories");
                }
                return _Histories;
            }
        }
        private ObjectSet<History> _Histories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Upload_Table> Upload_Table
        {
            get
            {
                if ((_Upload_Table == null))
                {
                    _Upload_Table = base.CreateObjectSet<Upload_Table>("Upload_Table");
                }
                return _Upload_Table;
            }
        }
        private ObjectSet<Upload_Table> _Upload_Table;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Admission_Table EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdmission_Table(Admission_Table admission_Table)
        {
            base.AddObject("Admission_Table", admission_Table);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CMS_Table EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCMS_Table(CMS_Table cMS_Table)
        {
            base.AddObject("CMS_Table", cMS_Table);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Histories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHistories(History history)
        {
            base.AddObject("Histories", history);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Upload_Table EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUpload_Table(Upload_Table upload_Table)
        {
            base.AddObject("Upload_Table", upload_Table);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CMSModel", Name="Admission_Table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Admission_Table : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Admission_Table object.
        /// </summary>
        /// <param name="applicationNo">Initial value of the ApplicationNo property.</param>
        public static Admission_Table CreateAdmission_Table(global::System.String applicationNo)
        {
            Admission_Table admission_Table = new Admission_Table();
            admission_Table.ApplicationNo = applicationNo;
            return admission_Table;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationNo
        {
            get
            {
                return _ApplicationNo;
            }
            set
            {
                if (_ApplicationNo != value)
                {
                    OnApplicationNoChanging(value);
                    ReportPropertyChanging("ApplicationNo");
                    _ApplicationNo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ApplicationNo");
                    OnApplicationNoChanged();
                }
            }
        }
        private global::System.String _ApplicationNo;
        partial void OnApplicationNoChanging(global::System.String value);
        partial void OnApplicationNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PreRegNo
        {
            get
            {
                return _PreRegNo;
            }
            set
            {
                OnPreRegNoChanging(value);
                ReportPropertyChanging("PreRegNo");
                _PreRegNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PreRegNo");
                OnPreRegNoChanged();
            }
        }
        private global::System.String _PreRegNo;
        partial void OnPreRegNoChanging(global::System.String value);
        partial void OnPreRegNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApplicantName
        {
            get
            {
                return _ApplicantName;
            }
            set
            {
                OnApplicantNameChanging(value);
                ReportPropertyChanging("ApplicantName");
                _ApplicantName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApplicantName");
                OnApplicantNameChanged();
            }
        }
        private global::System.String _ApplicantName;
        partial void OnApplicantNameChanging(global::System.String value);
        partial void OnApplicantNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Grade
        {
            get
            {
                return _Grade;
            }
            set
            {
                OnGradeChanging(value);
                ReportPropertyChanging("Grade");
                _Grade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Grade");
                OnGradeChanged();
            }
        }
        private global::System.String _Grade;
        partial void OnGradeChanging(global::System.String value);
        partial void OnGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AppliedDate
        {
            get
            {
                return _AppliedDate;
            }
            set
            {
                OnAppliedDateChanging(value);
                ReportPropertyChanging("AppliedDate");
                _AppliedDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AppliedDate");
                OnAppliedDateChanged();
            }
        }
        private global::System.String _AppliedDate;
        partial void OnAppliedDateChanging(global::System.String value);
        partial void OnAppliedDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CMSModel", Name="CMS_Table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CMS_Table : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CMS_Table object.
        /// </summary>
        /// <param name="issue">Initial value of the Issue property.</param>
        public static CMS_Table CreateCMS_Table(global::System.Int32 issue)
        {
            CMS_Table cMS_Table = new CMS_Table();
            cMS_Table.Issue = issue;
            return cMS_Table;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Issue
        {
            get
            {
                return _Issue;
            }
            set
            {
                if (_Issue != value)
                {
                    OnIssueChanging(value);
                    ReportPropertyChanging("Issue");
                    _Issue = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Issue");
                    OnIssueChanged();
                }
            }
        }
        private global::System.Int32 _Issue;
        partial void OnIssueChanging(global::System.Int32 value);
        partial void OnIssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserInbox
        {
            get
            {
                return _UserInbox;
            }
            set
            {
                OnUserInboxChanging(value);
                ReportPropertyChanging("UserInbox");
                _UserInbox = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserInbox");
                OnUserInboxChanged();
            }
        }
        private global::System.String _UserInbox;
        partial void OnUserInboxChanging(global::System.String value);
        partial void OnUserInboxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IssueType
        {
            get
            {
                return _IssueType;
            }
            set
            {
                OnIssueTypeChanging(value);
                ReportPropertyChanging("IssueType");
                _IssueType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IssueType");
                OnIssueTypeChanged();
            }
        }
        private global::System.String _IssueType;
        partial void OnIssueTypeChanging(global::System.String value);
        partial void OnIssueTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentName
        {
            get
            {
                return _StudentName;
            }
            set
            {
                OnStudentNameChanging(value);
                ReportPropertyChanging("StudentName");
                _StudentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentName");
                OnStudentNameChanged();
            }
        }
        private global::System.String _StudentName;
        partial void OnStudentNameChanging(global::System.String value);
        partial void OnStudentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String History
        {
            get
            {
                return _History;
            }
            set
            {
                OnHistoryChanging(value);
                ReportPropertyChanging("History");
                _History = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("History");
                OnHistoryChanged();
            }
        }
        private global::System.String _History;
        partial void OnHistoryChanging(global::System.String value);
        partial void OnHistoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IssueDate
        {
            get
            {
                return _IssueDate;
            }
            set
            {
                OnIssueDateChanging(value);
                ReportPropertyChanging("IssueDate");
                _IssueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IssueDate");
                OnIssueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _IssueDate;
        partial void OnIssueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnIssueDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CMSModel", Name="History")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class History : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new History object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static History CreateHistory(global::System.Int32 id)
        {
            History history = new History();
            history.Id = id;
            return history;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Issue
        {
            get
            {
                return _Issue;
            }
            set
            {
                OnIssueChanging(value);
                ReportPropertyChanging("Issue");
                _Issue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Issue");
                OnIssueChanged();
            }
        }
        private Nullable<global::System.Int32> _Issue;
        partial void OnIssueChanging(Nullable<global::System.Int32> value);
        partial void OnIssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CommentedBy
        {
            get
            {
                return _CommentedBy;
            }
            set
            {
                OnCommentedByChanging(value);
                ReportPropertyChanging("CommentedBy");
                _CommentedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CommentedBy");
                OnCommentedByChanged();
            }
        }
        private global::System.String _CommentedBy;
        partial void OnCommentedByChanging(global::System.String value);
        partial void OnCommentedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CommentedOn
        {
            get
            {
                return _CommentedOn;
            }
            set
            {
                OnCommentedOnChanging(value);
                ReportPropertyChanging("CommentedOn");
                _CommentedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommentedOn");
                OnCommentedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CommentedOn;
        partial void OnCommentedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCommentedOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CMSModel", Name="Upload_Table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Upload_Table : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Upload_Table object.
        /// </summary>
        /// <param name="upload_Id">Initial value of the Upload_Id property.</param>
        public static Upload_Table CreateUpload_Table(global::System.Int32 upload_Id)
        {
            Upload_Table upload_Table = new Upload_Table();
            upload_Table.Upload_Id = upload_Id;
            return upload_Table;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Upload_Id
        {
            get
            {
                return _Upload_Id;
            }
            set
            {
                if (_Upload_Id != value)
                {
                    OnUpload_IdChanging(value);
                    ReportPropertyChanging("Upload_Id");
                    _Upload_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Upload_Id");
                    OnUpload_IdChanged();
                }
            }
        }
        private global::System.Int32 _Upload_Id;
        partial void OnUpload_IdChanging(global::System.Int32 value);
        partial void OnUpload_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Issue
        {
            get
            {
                return _Issue;
            }
            set
            {
                OnIssueChanging(value);
                ReportPropertyChanging("Issue");
                _Issue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Issue");
                OnIssueChanged();
            }
        }
        private Nullable<global::System.Int32> _Issue;
        partial void OnIssueChanging(Nullable<global::System.Int32> value);
        partial void OnIssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileId
        {
            get
            {
                return _FileId;
            }
            set
            {
                OnFileIdChanging(value);
                ReportPropertyChanging("FileId");
                _FileId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileId");
                OnFileIdChanged();
            }
        }
        private global::System.String _FileId;
        partial void OnFileIdChanging(global::System.String value);
        partial void OnFileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UploadedOn
        {
            get
            {
                return _UploadedOn;
            }
            set
            {
                OnUploadedOnChanging(value);
                ReportPropertyChanging("UploadedOn");
                _UploadedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UploadedOn");
                OnUploadedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _UploadedOn;
        partial void OnUploadedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnUploadedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UploadedBy
        {
            get
            {
                return _UploadedBy;
            }
            set
            {
                OnUploadedByChanging(value);
                ReportPropertyChanging("UploadedBy");
                _UploadedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UploadedBy");
                OnUploadedByChanged();
            }
        }
        private global::System.String _UploadedBy;
        partial void OnUploadedByChanging(global::System.String value);
        partial void OnUploadedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdateStatus
        {
            get
            {
                return _UpdateStatus;
            }
            set
            {
                OnUpdateStatusChanging(value);
                ReportPropertyChanging("UpdateStatus");
                _UpdateStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdateStatus");
                OnUpdateStatusChanged();
            }
        }
        private global::System.String _UpdateStatus;
        partial void OnUpdateStatusChanging(global::System.String value);
        partial void OnUpdateStatusChanged();

        #endregion

    
    }

    #endregion

    
}
