using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.Serialization;

namespace TIPS.Entities.Assess
{
    [DataContract]
    public class ComparativeFAHWReport_Vw
    {
        [DataMember]
        public virtual long Id { get; set; }
        [DataMember]
        public virtual long AssessId { get; set; }
        [DataMember]
        public virtual string Name { get; set; }
        [DataMember]
        public virtual string IdNo { get; set; }
        [DataMember]
        public virtual string Campus { get; set; }
        [DataMember]
        public virtual string Section { get; set; }
        [DataMember]
        public virtual string Grade { get; set; }
        [DataMember]
        public virtual string AcademicYear { get; set; }

        public virtual string HWBioJan { get; set; }
        public virtual string HWBioFeb { get; set; }
        public virtual string HWBioMar { get; set; }
        public virtual string HWBioApr { get; set; }
        public virtual string HWBioJun { get; set; }
        public virtual string HWBioJly { get; set; }
        public virtual string HWBioAug { get; set; }
        public virtual string HWBioSep { get; set; }
        public virtual string HWBioOct { get; set; }
        public virtual string HWBioNov { get; set; }
        public virtual string HWBioDec { get; set; }
        public virtual string HWChemJan { get; set; }
        public virtual string HWChemFeb { get; set; }
        public virtual string HWChemMar { get; set; }
        public virtual string HWChemApr { get; set; }
        public virtual string HWChemJun { get; set; }
        public virtual string HWChemJly { get; set; }
        public virtual string HWChemAug { get; set; }
        public virtual string HWChemSep { get; set; }
        public virtual string HWChemOct { get; set; }
        public virtual string HWChemNov { get; set; }
        public virtual string HWChemDec { get; set; }
        public virtual string HWComSciJan { get; set; }
        public virtual string HWComSciFeb { get; set; }
        public virtual string HWComSciMar { get; set; }
        public virtual string HWComSciApr { get; set; }
        public virtual string HWComSciJun { get; set; }
        public virtual string HWComSciJly { get; set; }
        public virtual string HWComSciAug { get; set; }
        public virtual string HWComSciSep { get; set; }
        public virtual string HWComSciOct { get; set; }
        public virtual string HWComSciNov { get; set; }
        public virtual string HWComSciDec { get; set; }
        public virtual string HWEcoJan { get; set; }
        public virtual string HWEcoFeb { get; set; }
        public virtual string HWEcoMar { get; set; }
        public virtual string HWEcoApr { get; set; }
        public virtual string HWEcoJun { get; set; }
        public virtual string HWEcoJly { get; set; }
        public virtual string HWEcoAug { get; set; }
        public virtual string HWEcoSep { get; set; }
        public virtual string HWEcoOct { get; set; }
        public virtual string HWEcoNov { get; set; }
        public virtual string HWEcoDec { get; set; }
        public virtual string HWEngJan { get; set; }
        public virtual string HWEngFeb { get; set; }
        public virtual string HWEngMar { get; set; }
        public virtual string HWEngApr { get; set; }
        public virtual string HWEngJun { get; set; }
        public virtual string HWEngJly { get; set; }
        public virtual string HWEngAug { get; set; }
        public virtual string HWEngSep { get; set; }
        public virtual string HWEngOct { get; set; }
        public virtual string HWEngNov { get; set; }
        public virtual string HWEngDec { get; set; }
        public virtual string HWFreJan { get; set; }
        public virtual string HWFreFeb { get; set; }
        public virtual string HWFreMar { get; set; }
        public virtual string HWFreApr { get; set; }
        public virtual string HWFreJun { get; set; }
        public virtual string HWFreJly { get; set; }
        public virtual string HWFreAug { get; set; }
        public virtual string HWFreSep { get; set; }
        public virtual string HWFreOct { get; set; }
        public virtual string HWFreNov { get; set; }
        public virtual string HWFreDec { get; set; }
        public virtual string HWHinJan { get; set; }
        public virtual string HWHinFeb { get; set; }
        public virtual string HWHinMar { get; set; }
        public virtual string HWHinApr { get; set; }
        public virtual string HWHinJun { get; set; }
        public virtual string HWHinJly { get; set; }
        public virtual string HWHinAug { get; set; }
        public virtual string HWHinSep { get; set; }
        public virtual string HWHinOct { get; set; }
        public virtual string HWHinNov { get; set; }
        public virtual string HWHinDec { get; set; }
        public virtual string HWHisGeoJan { get; set; }
        public virtual string HWHisGeoFeb { get; set; }
        public virtual string HWHisGeoMar { get; set; }
        public virtual string HWHisGeoApr { get; set; }
        public virtual string HWHisGeoJun { get; set; }
        public virtual string HWHisGeoJly { get; set; }
        public virtual string HWHisGeoAug { get; set; }
        public virtual string HWHisGeoSep { get; set; }
        public virtual string HWHisGeoOct { get; set; }
        public virtual string HWHisGeoNov { get; set; }
        public virtual string HWHisGeoDec { get; set; }
        public virtual string HWIctJan { get; set; }
        public virtual string HWIctFeb { get; set; }
        public virtual string HWIctMar { get; set; }
        public virtual string HWIctApr { get; set; }
        public virtual string HWIctJun { get; set; }
        public virtual string HWIctJly { get; set; }
        public virtual string HWIctAug { get; set; }
        public virtual string HWIctSep { get; set; }
        public virtual string HWIctOct { get; set; }
        public virtual string HWIctNov { get; set; }
        public virtual string HWIctDec { get; set; }
        public virtual string HWMatJan { get; set; }
        public virtual string HWMatFeb { get; set; }
        public virtual string HWMatMar { get; set; }
        public virtual string HWMatApr { get; set; }
        public virtual string HWMatJun { get; set; }
        public virtual string HWMatJly { get; set; }
        public virtual string HWMatAug { get; set; }
        public virtual string HWMatSep { get; set; }
        public virtual string HWMatOct { get; set; }
        public virtual string HWMatNov { get; set; }
        public virtual string HWMatDec { get; set; }
        public virtual string HWPhyEduJan { get; set; }
        public virtual string HWPhyEduFeb { get; set; }
        public virtual string HWPhyEduMar { get; set; }
        public virtual string HWPhyEduApr { get; set; }
        public virtual string HWPhyEduJun { get; set; }
        public virtual string HWPhyEduJly { get; set; }
        public virtual string HWPhyEduAug { get; set; }
        public virtual string HWPhyEduSep { get; set; }
        public virtual string HWPhyEduOct { get; set; }
        public virtual string HWPhyEduNov { get; set; }
        public virtual string HWPhyEduDec { get; set; }
        public virtual string HWPhyJan { get; set; }
        public virtual string HWPhyFeb { get; set; }
        public virtual string HWPhyMar { get; set; }
        public virtual string HWPhyApr { get; set; }
        public virtual string HWPhyJun { get; set; }
        public virtual string HWPhyJly { get; set; }
        public virtual string HWPhyAug { get; set; }
        public virtual string HWPhySep { get; set; }
        public virtual string HWPhyOct { get; set; }
        public virtual string HWPhyNov { get; set; }
        public virtual string HWPhyDec { get; set; }

        public virtual string FABioJan { get; set; }
        public virtual string FABioFeb { get; set; }
        public virtual string FABioMar { get; set; }
        public virtual string FABioApr { get; set; }
        public virtual string FABioJun { get; set; }
        public virtual string FABioJly { get; set; }
        public virtual string FABioAug { get; set; }
        public virtual string FABioSep { get; set; }
        public virtual string FABioOct { get; set; }
        public virtual string FABioNov { get; set; }
        public virtual string FABioDec { get; set; }
        public virtual string FAChemJan { get; set; }
        public virtual string FAChemFeb { get; set; }
        public virtual string FAChemMar { get; set; }
        public virtual string FAChemApr { get; set; }
        public virtual string FAChemJun { get; set; }
        public virtual string FAChemJly { get; set; }
        public virtual string FAChemAug { get; set; }
        public virtual string FAChemSep { get; set; }
        public virtual string FAChemOct { get; set; }
        public virtual string FAChemNov { get; set; }
        public virtual string FAChemDec { get; set; }
        public virtual string FAComSciJan { get; set; }
        public virtual string FAComSciFeb { get; set; }
        public virtual string FAComSciMar { get; set; }
        public virtual string FAComSciApr { get; set; }
        public virtual string FAComSciJun { get; set; }
        public virtual string FAComSciJly { get; set; }
        public virtual string FAComSciAug { get; set; }
        public virtual string FAComSciSep { get; set; }
        public virtual string FAComSciOct { get; set; }
        public virtual string FAComSciNov { get; set; }
        public virtual string FAComSciDec { get; set; }
        public virtual string FAEcoJan { get; set; }
        public virtual string FAEcoFeb { get; set; }
        public virtual string FAEcoMar { get; set; }
        public virtual string FAEcoApr { get; set; }
        public virtual string FAEcoJun { get; set; }
        public virtual string FAEcoJly { get; set; }
        public virtual string FAEcoAug { get; set; }
        public virtual string FAEcoSep { get; set; }
        public virtual string FAEcoOct { get; set; }
        public virtual string FAEcoNov { get; set; }
        public virtual string FAEcoDec { get; set; }
        public virtual string FAEngJan { get; set; }
        public virtual string FAEngFeb { get; set; }
        public virtual string FAEngMar { get; set; }
        public virtual string FAEngApr { get; set; }
        public virtual string FAEngJun { get; set; }
        public virtual string FAEngJly { get; set; }
        public virtual string FAEngAug { get; set; }
        public virtual string FAEngSep { get; set; }
        public virtual string FAEngOct { get; set; }
        public virtual string FAEngNov { get; set; }
        public virtual string FAEngDec { get; set; }
        public virtual string FAFreJan { get; set; }
        public virtual string FAFreFeb { get; set; }
        public virtual string FAFreMar { get; set; }
        public virtual string FAFreApr { get; set; }
        public virtual string FAFreJun { get; set; }
        public virtual string FAFreJly { get; set; }
        public virtual string FAFreAug { get; set; }
        public virtual string FAFreSep { get; set; }
        public virtual string FAFreOct { get; set; }
        public virtual string FAFreNov { get; set; }
        public virtual string FAFreDec { get; set; }
        public virtual string FAHinJan { get; set; }
        public virtual string FAHinFeb { get; set; }
        public virtual string FAHinMar { get; set; }
        public virtual string FAHinApr { get; set; }
        public virtual string FAHinJun { get; set; }
        public virtual string FAHinJly { get; set; }
        public virtual string FAHinAug { get; set; }
        public virtual string FAHinSep { get; set; }
        public virtual string FAHinOct { get; set; }
        public virtual string FAHinNov { get; set; }
        public virtual string FAHinDec { get; set; }
        public virtual string FAHisGeoJan { get; set; }
        public virtual string FAHisGeoFeb { get; set; }
        public virtual string FAHisGeoMar { get; set; }
        public virtual string FAHisGeoApr { get; set; }
        public virtual string FAHisGeoJun { get; set; }
        public virtual string FAHisGeoJly { get; set; }
        public virtual string FAHisGeoAug { get; set; }
        public virtual string FAHisGeoSep { get; set; }
        public virtual string FAHisGeoOct { get; set; }
        public virtual string FAHisGeoNov { get; set; }
        public virtual string FAHisGeoDec { get; set; }
        public virtual string FAIctJan { get; set; }
        public virtual string FAIctFeb { get; set; }
        public virtual string FAIctMar { get; set; }
        public virtual string FAIctApr { get; set; }
        public virtual string FAIctJun { get; set; }
        public virtual string FAIctJly { get; set; }
        public virtual string FAIctAug { get; set; }
        public virtual string FAIctSep { get; set; }
        public virtual string FAIctOct { get; set; }
        public virtual string FAIctNov { get; set; }
        public virtual string FAIctDec { get; set; }
        public virtual string FAMatJan { get; set; }
        public virtual string FAMatFeb { get; set; }
        public virtual string FAMatMar { get; set; }
        public virtual string FAMatApr { get; set; }
        public virtual string FAMatJun { get; set; }
        public virtual string FAMatJly { get; set; }
        public virtual string FAMatAug { get; set; }
        public virtual string FAMatSep { get; set; }
        public virtual string FAMatOct { get; set; }
        public virtual string FAMatNov { get; set; }
        public virtual string FAMatDec { get; set; }
        public virtual string FAPhyEduJan { get; set; }
        public virtual string FAPhyEduFeb { get; set; }
        public virtual string FAPhyEduMar { get; set; }
        public virtual string FAPhyEduApr { get; set; }
        public virtual string FAPhyEduJun { get; set; }
        public virtual string FAPhyEduJly { get; set; }
        public virtual string FAPhyEduAug { get; set; }
        public virtual string FAPhyEduSep { get; set; }
        public virtual string FAPhyEduOct { get; set; }
        public virtual string FAPhyEduNov { get; set; }
        public virtual string FAPhyEduDec { get; set; }
        public virtual string FAPhyJan { get; set; }
        public virtual string FAPhyFeb { get; set; }
        public virtual string FAPhyMar { get; set; }
        public virtual string FAPhyApr { get; set; }
        public virtual string FAPhyJun { get; set; }
        public virtual string FAPhyJly { get; set; }
        public virtual string FAPhyAug { get; set; }
        public virtual string FAPhySep { get; set; }
        public virtual string FAPhyOct { get; set; }
        public virtual string FAPhyNov { get; set; }
        public virtual string FAPhyDec { get; set; }
    }
}
