using System.Collections.Generic;
using System.Text;
using System;
namespace TIPS.Entities.Assess.ReportCardClasses
{
    public class RptCardMYP
    {
        public virtual long Id { get; set; }
        public virtual long StudentId { get; set; }
        public virtual string Name { get; set; }
        public virtual string RequestNo { get; set; }
        public virtual string IdNo { get; set; }
        public virtual string Grade { get; set; }
        public virtual string Section { get; set; }
        public virtual string Campus { get; set; }
        public virtual string AcademicYear { get; set; }
        public virtual long Semester { get; set; }
        public virtual long PreRegNum { get; set; }
        public virtual string TeacherName { get; set; }
        public virtual string RptCardStatus { get; set; }
        public virtual string Second_Language { get; set; }
        public virtual DateTime? RptDate { get; set; }
        public virtual string SubjGrd_Eng { get; set; }
        public virtual string SubjGrd_Second_Lang { get; set; }
        public virtual string SubjGrd_Maths { get; set; }
        public virtual string SubjGrd_Phys { get; set; }
        public virtual string SubjGrd_Chstr { get; set; }
        public virtual string SubjGrd_Bio { get; set; }
        public virtual string SubjGrd_HisGeo { get; set; }
        public virtual string SubjGrd_ICT { get; set; }
        public virtual string Eng_WrtSkl_Ach_Cntnt { get; set; }
        public virtual string Eng_WrtSkl_Ach_Audn { get; set; }
        public virtual string Eng_WrtSkl_Ach_Purps { get; set; }
        public virtual string Eng_WrtSkl_Ach_TxtStr { get; set; }
        public virtual string Eng_WrtSkl_Ach_SenStr { get; set; }
        public virtual string Eng_WrtSkl_Ach_Vocblry { get; set; }
        public virtual string Eng_WrtSkl_Ach_Splng { get; set; }
        public virtual string Eng_WrtSkl_Efrt_Cntnt { get; set; }
        public virtual string Eng_WrtSkl_Efrt_Audn { get; set; }
        public virtual string Eng_WrtSkl_Efrt_Purps { get; set; }
        public virtual string Eng_WrtSkl_Efrt_TxtStr { get; set; }
        public virtual string Eng_WrtSkl_Efrt_SenStr { get; set; }
        public virtual string Eng_WrtSkl_Efrt_Vocblry { get; set; }
        public virtual string Eng_WrtSkl_Efrt_Splng { get; set; }
        public virtual string Eng_OAW_Skl_Cmprsn { get; set; }
        public virtual string Eng_OAW_Skl_Grmr { get; set; }
        public virtual string Eng_OAW_Skl_Punctn { get; set; }
        public virtual string Eng_OAW_Skl_NartvElmnts { get; set; }
        public virtual string Eng_OAW_Efrt_Cmprsn { get; set; }
        public virtual string Eng_OAW_Efrt_Grmr { get; set; }
        public virtual string Eng_OAW_Efrt_Punctn { get; set; }
        public virtual string Eng_OAW_Efrt_NartvElmnts { get; set; }
        public virtual string Eng_LSS_Skl_Confdnc { get; set; }
        public virtual string Eng_LSS_Skl_Flncy { get; set; }
        public virtual string Eng_LSS_Skl_Pronctn { get; set; }
        public virtual string Eng_LSS_Skl_udstnd { get; set; }
        public virtual string Eng_LSS_Skl_vcblry { get; set; }
        public virtual string Eng_LSS_Efrt_Confdnc { get; set; }
        public virtual string Eng_LSS_Efrt_Flncy { get; set; }
        public virtual string Eng_LSS_Efrt_Pronctn { get; set; }
        public virtual string Eng_LSS_Efrt_udstnd { get; set; }
        public virtual string Eng_LSS_Efrt_vcblry { get; set; }
        public virtual string Second_Lng_WrtSkl_Skl_Splng { get; set; }
        public virtual string Second_Lng_WrtSkl_Skl_Vocblry { get; set; }
        public virtual string Second_Lng_WrtSkl_Skl_Punctn { get; set; }
        public virtual string Second_Lng_WrtSkl_Skl_Grmr { get; set; }
        public virtual string Second_Lng_WrtSkl_Skl_IdsCntnt { get; set; }
        public virtual string Second_Lng_WrtSkl_Skl_NetnsHndwrt { get; set; }
        public virtual string Second_Lng_WrtSkl_Efrt_Splng { get; set; }
        public virtual string Second_Lng_WrtSkl_Efrt_Vocblry { get; set; }
        public virtual string Second_Lng_WrtSkl_Efrt_Punctn { get; set; }
        public virtual string Second_Lng_WrtSkl_Efrt_Grmr { get; set; }
        public virtual string Second_Lng_WrtSkl_Efrt_IdsCntnt { get; set; }
        public virtual string Second_Lng_WrtSkl_Efrt_NetnsHndwrt { get; set; }
        public virtual string Second_Lng_RdgSkl_Skl_Confdnc { get; set; }
        public virtual string Second_Lng_RdgSkl_Skl_Flncy { get; set; }
        public virtual string Second_Lng_RdgSkl_Skl_TonInTon { get; set; }
        public virtual string Second_Lng_RdgSkl_Skl_Pronctn { get; set; }
        public virtual string Second_Lng_RdgSkl_Skl_udstnd { get; set; }
        public virtual string Second_Lng_RdgSkl_Efrt_Confdnc { get; set; }
        public virtual string Second_Lng_RdgSkl_Efrt_Flncy { get; set; }
        public virtual string Second_Lng_RdgSkl_Efrt_TonInTon { get; set; }
        public virtual string Second_Lng_RdgSkl_Efrt_Pronctn { get; set; }
        public virtual string Second_Lng_RdgSkl_Efrt_udstnd { get; set; }
        public virtual string Second_Lng_LSS_Skl_Confdnc { get; set; }
        public virtual string Second_Lng_LSS_Skl_Flncy { get; set; }
        public virtual string Second_Lng_LSS_Skl_Pronctn { get; set; }
        public virtual string Second_Lng_LSS_Skl_udstnd { get; set; }
        public virtual string Second_Lng_LSS_Skl_Vocblry { get; set; }
        public virtual string Second_Lng_LSS_Efrt_Confdnc { get; set; }
        public virtual string Second_Lng_LSS_Efrt_Flncy { get; set; }
        public virtual string Second_Lng_LSS_Efrt_Pronctn { get; set; }
        public virtual string Second_Lng_LSS_Efrt_udstnd { get; set; }
        public virtual string Second_Lng_LSS_Efrt_Vocblry { get; set; }
        public virtual string Maths_Ach_KnwdUndstnd { get; set; }
        public virtual string Maths_Ach_UsgApprMathdsRespn { get; set; }
        public virtual string Maths_Ach_PrblmSlvng { get; set; }
        public virtual string Maths_Ach_TechSkill { get; set; }
        public virtual string Maths_Ach_MntlAblty { get; set; }
        public virtual string Maths_Efrt_KnwdUndstnd { get; set; }
        public virtual string Maths_Efrt_UsgApprMathdsRespn { get; set; }
        public virtual string Maths_Efrt_PrblmSlvng { get; set; }
        public virtual string Maths_Efrt_TechSkill { get; set; }
        public virtual string Maths_Efrt_MntlAblty { get; set; }
        public virtual string Phys_Ach_RclScnInfo { get; set; }
        public virtual string Phys_Ach_UsgApprScnficLang { get; set; }
        public virtual string Phys_Ach_ScnficInq { get; set; }
        public virtual string Phys_Ach_ScnficAppn { get; set; }
        public virtual string Phys_Ach_IntrptnScnficData { get; set; }
        public virtual string Phys_Ach_TechSkill { get; set; }
        public virtual string Phys_Efrt_RclScnInfo { get; set; }
        public virtual string Phys_Efrt_UsgApprScnficLang { get; set; }
        public virtual string Phys_Efrt_ScnficInq { get; set; }
        public virtual string Phys_Efrt_ScnficAppn { get; set; }
        public virtual string Phys_Efrt_IntrptnScnficData { get; set; }
        public virtual string Phys_Efrt_TechSkill { get; set; }
        public virtual string Chstr_Ach_RclScnInfo { get; set; }
        public virtual string Chstr_Ach_UsgApprScnficLang { get; set; }
        public virtual string Chstr_Ach_ScnficInq { get; set; }
        public virtual string Chstr_Ach_ScnficAppn { get; set; }
        public virtual string Chstr_Ach_IntrptnScnficData { get; set; }
        public virtual string Chstr_Ach_TechSkill { get; set; }
        public virtual string Chstr_Efrt_RclScnInfo { get; set; }
        public virtual string Chstr_Efrt_UsgApprScnficLang { get; set; }
        public virtual string Chstr_Efrt_ScnficInq { get; set; }
        public virtual string Chstr_Efrt_ScnficAppn { get; set; }
        public virtual string Chstr_Efrt_IntrptnScnficData { get; set; }
        public virtual string Chstr_Efrt_TechSkill { get; set; }
        public virtual string Bio_Ach_RclScnInfo { get; set; }
        public virtual string Bio_Ach_UsgApprScnficLang { get; set; }
        public virtual string Bio_Ach_ScnficInq { get; set; }
        public virtual string Bio_Ach_ScnficAppn { get; set; }
        public virtual string Bio_Ach_IntrptnScnficData { get; set; }
        public virtual string Bio_Ach_TechSkill { get; set; }
        public virtual string Bio_Efrt_RclScnInfo { get; set; }
        public virtual string Bio_Efrt_UsgApprScnficLang { get; set; }
        public virtual string Bio_Efrt_ScnficInq { get; set; }
        public virtual string Bio_Efrt_ScnficAppn { get; set; }
        public virtual string Bio_Efrt_IntrptnScnficData { get; set; }
        public virtual string Bio_Efrt_TechSkill { get; set; }
        public virtual string HisGeo_Ach_UndrsndConcpt { get; set; }
        public virtual string HisGeo_Ach_RsrchSkl { get; set; }
        public virtual string HisGeo_Ach_OrgnPrsntn { get; set; }
        public virtual string HisGeo_Ach_RclInfo { get; set; }
        public virtual string HisGeo_Efrt_UndrsndConcpt { get; set; }
        public virtual string HisGeo_Efrt_RsrchSkl { get; set; }
        public virtual string HisGeo_Efrt_OrgnPrsntn { get; set; }
        public virtual string HisGeo_Efrt_RclInfo { get; set; }
        public virtual string ICT_Ach_RclInfo { get; set; }
        public virtual string ICT_Ach_Invtgt { get; set; }
        public virtual string ICT_Ach_Plnng { get; set; }
        public virtual string ICT_Ach_AppnOfTech { get; set; }
        public virtual string ICT_Efrt_RclInfo { get; set; }
        public virtual string ICT_Efrt_Invtgt { get; set; }
        public virtual string ICT_Efrt_Plnng { get; set; }
        public virtual string ICT_Efrt_AppnOfTech { get; set; }
        public virtual string Rbt_Ach_KnwdUndstnd { get; set; }
        public virtual string Rbt_Ach_BldngDsgn { get; set; }
        public virtual string Rbt_Ach_Progm { get; set; }
        public virtual string Rbt_Ach_WrkgInTam { get; set; }
        public virtual string Rbt_Efrt_KnwdUndstnd { get; set; }
        public virtual string Rbt_Efrt_BldngDsgn { get; set; }
        public virtual string Rbt_Efrt_Progm { get; set; }
        public virtual string Rbt_Efrt_WrkgInTam { get; set; }
        public virtual string PhysEd_Ach_Bhvr { get; set; }
        public virtual string PhysEd_Ach_TmWrk { get; set; }
        public virtual string PhysEd_Ach_BscSkl { get; set; }
        public virtual string PhysEd_Ach_Ftns { get; set; }
        public virtual string PhysEd_Efrt_Bhvr { get; set; }
        public virtual string PhysEd_Efrt_TmWrk { get; set; }
        public virtual string PhysEd_Efrt_BscSkl { get; set; }
        public virtual string PhysEd_Efrt_Ftns { get; set; }
        public virtual string FnArt_Musc_Ach_Prtcpn { get; set; }
        public virtual string FnArt_Musc_Ach_Bhvr { get; set; }
        public virtual string FnArt_Musc_Ach_ShwKwdUntStuds { get; set; }
        public virtual string FnArt_Musc_Efrt_Prtcpn { get; set; }
        public virtual string FnArt_Musc_Efrt_Bhvr { get; set; }
        public virtual string FnArt_Musc_Efrt_ShwKwdUntStuds { get; set; }
        public virtual string FnArt_Dnc_Ach_SklTech { get; set; }
        public virtual string FnArt_Dnc_Ach_PrblmSlvng { get; set; }
        public virtual string FnArt_Dnc_Ach_Clbrtn { get; set; }
        public virtual string FnArt_Dnc_Efrt_SklTech { get; set; }
        public virtual string FnArt_Dnc_Efrt_PrblmSlvng { get; set; }
        public virtual string FnArt_Dnc_Efrt_Clbrtn { get; set; }
        public virtual string RptCardCreatedBy { get; set; }
        public virtual DateTime? RptCardCreatedDate { get; set; }
        public virtual string RptCardModifiedBy { get; set; }
        public virtual DateTime? RptCardModifiedDate { get; set; }
        public virtual RptCardFocus RptCardFocus { get; set; }
        //Added By Gobi
        public virtual string Initial { get; set; }

        public virtual string spark_Eval_ExperiSkil { get; set; }
        public virtual string spark_Eval_TeamWork { get; set; }
        public virtual string spark_Eval_AttforLearn { get; set; }
        public virtual string spark_Eval_WrittenTask { get; set; }
    }
}