//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        internal static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRAND.
        /// </summary>
        internal static string tbl1ENGR1C1 {
            get {
                return ResourceManager.GetString("tbl1ENGR1C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY ELEMENTS.
        /// </summary>
        internal static string tbl1ENGR1C2 {
            get {
                return ResourceManager.GetString("tbl1ENGR1C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPECTATIONS.
        /// </summary>
        internal static string tbl1ENGR1C3 {
            get {
                return ResourceManager.GetString("tbl1ENGR1C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOMPLISHED.
        /// </summary>
        internal static string tbl1ENGR1C4 {
            get {
                return ResourceManager.GetString("tbl1ENGR1C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRESSING.
        /// </summary>
        internal static string tbl1ENGR1C5 {
            get {
                return ResourceManager.GetString("tbl1ENGR1C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEEDS ENCOURAGEMENT.
        /// </summary>
        internal static string tbl1ENGR1C6 {
            get {
                return ResourceManager.GetString("tbl1ENGR1C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPS.
        /// </summary>
        internal static string tips {
            get {
                return ResourceManager.GetString("tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE INDIAN PUBLIC SCHOOL.
        /// </summary>
        internal static string tipsfull {
            get {
                return ResourceManager.GetString("tipsfull", resourceCulture);
            }
        }
    }
}
